# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\tcortexops\"#\n\x0eMetricsRequest\x12\x11\n\trequester\x18\x01 \x01(\t\"E\n\x0b\x43PUResponse\x12\x13\n\x0b\x63pu_percent\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"K\n\x0eMemoryResponse\x12\x16\n\x0ememory_percent\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"G\n\x0c\x44iskResponse\x12\x14\n\x0c\x64isk_percent\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"\x9c\x01\n\x12\x41llMetricsResponse\x12\x13\n\x0b\x63pu_percent\x18\x01 \x01(\x01\x12\x16\n\x0ememory_percent\x18\x02 \x01(\x01\x12\x14\n\x0c\x64isk_percent\x18\x03 \x01(\x01\x12\x19\n\x11reliability_score\x18\x04 \x01(\x05\x12\x15\n\rhealth_status\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"\x8e\x01\n\x0e\x41nalyzeRequest\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x01\x12\x0e\n\x06memory\x18\x02 \x01(\x01\x12\x0c\n\x04\x64isk\x18\x03 \x01(\x01\x12\x1a\n\x12\x63ontainers_running\x18\x04 \x01(\x05\x12\x1a\n\x12\x63ontainers_stopped\x18\x05 \x01(\x05\x12\x19\n\x11reliability_score\x18\x06 \x01(\x05\"6\n\x0f\x41nalyzeResponse\x12\x10\n\x08\x61nalysis\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\x9a\x02\n\x0eMetricsService\x12;\n\x06GetCPU\x12\x19.cortexops.MetricsRequest\x1a\x16.cortexops.CPUResponse\x12\x41\n\tGetMemory\x12\x19.cortexops.MetricsRequest\x1a\x19.cortexops.MemoryResponse\x12=\n\x07GetDisk\x12\x19.cortexops.MetricsRequest\x1a\x17.cortexops.DiskResponse\x12I\n\rGetAllMetrics\x12\x19.cortexops.MetricsRequest\x1a\x1d.cortexops.AllMetricsResponse2[\n\tAIService\x12N\n\x15\x41nalyzeInfrastructure\x12\x19.cortexops.AnalyzeRequest\x1a\x1a.cortexops.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSREQUEST']._serialized_start=28
  _globals['_METRICSREQUEST']._serialized_end=63
  _globals['_CPURESPONSE']._serialized_start=65
  _globals['_CPURESPONSE']._serialized_end=134
  _globals['_MEMORYRESPONSE']._serialized_start=136
  _globals['_MEMORYRESPONSE']._serialized_end=211
  _globals['_DISKRESPONSE']._serialized_start=213
  _globals['_DISKRESPONSE']._serialized_end=284
  _globals['_ALLMETRICSRESPONSE']._serialized_start=287
  _globals['_ALLMETRICSRESPONSE']._serialized_end=443
  _globals['_ANALYZEREQUEST']._serialized_start=446
  _globals['_ANALYZEREQUEST']._serialized_end=588
  _globals['_ANALYZERESPONSE']._serialized_start=590
  _globals['_ANALYZERESPONSE']._serialized_end=644
  _globals['_METRICSSERVICE']._serialized_start=647
  _globals['_METRICSSERVICE']._serialized_end=929
  _globals['_AISERVICE']._serialized_start=931
  _globals['_AISERVICE']._serialized_end=1022
# @@protoc_insertion_point(module_scope)
